---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
type: Opaque
data:
  discord_bot_token: {{ .Values.discord.bot_token | b64enc }}
  spreadsheet_id: {{ .Values.spreadsheet_id | b64enc }}
